const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const {webcrypto,createHash}=require('node:crypto');
const {node}=require('./helpers/app.js');
const root=path.resolve(__dirname,'..');
const sha=x=>createHash('sha256').update(x).digest('hex');
let fixture;
async function built(){
 if(!fixture)fixture=(async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'well-body-pwa-'));const {buildPwa}=await import('../scripts/build-pwa.mjs');const release=await buildPwa(root,dir,Buffer.from('{"foods":[]}'));const contents=new Map();for(const a of release.assets)contents.set(a.url,await fs.readFile(path.join(dir,a.url.slice(2))));return {dir,release,contents};})();
 return fixture;
}
async function until(fn){const end=Date.now()+3000;while(!fn()){if(Date.now()>end)throw Error('Timed out');await new Promise(r=>setTimeout(r,5));}}
async function boot(options={}){
 const f=await built(),nodes=new Proxy({}, {get:(o,k)=>o[k]||(o[k]=node())}),data=new Map([['wellBodyWeightRecords','[{"date":"2020-01-01","weight":80}]']]),writes=[];
 const buttons=[{disabled:true}],executed=[];
 const ctx=vm.createContext({console,crypto:webcrypto,Blob,URL,TextDecoder,Uint8Array,navigator:{},setTimeout,
 localStorage:{getItem:k=>data.get(k)??null,setItem(k,v){writes.push(k);data.set(k,v)},removeItem(k){writes.push(k);data.delete(k)}},
 document:{getElementById:k=>nodes[k],querySelectorAll:()=>buttons,createElement:()=>node(),createTextNode:v=>({textContent:v}),head:{appendChild:async script=>{try{const text=await (await fetch(script.src)).text();executed.push(text);vm.runInContext(text,ctx);script.onload();}catch(e){script.onerror(e);}}}},
 fetch:async url=>{const a=f.release.assets.find(a=>a.url===url);if(options.failed===a.name)throw Error('synthetic network failure');return new Response(options.mixed===a.name?'OLD_SCRIPT_OR_HTML':f.contents.get(a.url));}});
 ctx.window=ctx;ctx.WB_RELEASE={id:f.release.id,assets:f.release.assets.filter(a=>a.name!=='index.html')};
 vm.runInContext(await fs.readFile(path.join(root,'pwa-boot.js'),'utf8'),ctx);
 return {ctx,nodes,data,writes,buttons,executed,f,run:code=>vm.runInContext(code,ctx)};
}
async function worker(options={}){
 const f=await built(),listeners={},maps=options.maps||new Map([['other-cache',new Map()],['well-body-app-v4',new Map()]]),deleted=[];
 const absolute=u=>new URL(typeof u==='string'?u:u.url,'https://isolated.invalid/').href;
 const caches={open:async name=>{if(!maps.has(name))maps.set(name,new Map());const m=maps.get(name);return {match:async url=>m.get(absolute(url))?.clone(),put:async(url,response)=>{if(options.putFailure)throw Error('synthetic quota');m.set(absolute(url),response.clone())}};},delete:async name=>{deleted.push(name);return maps.delete(name)}};
 vm.runInNewContext(await fs.readFile(path.join(f.dir,'service-worker.js'),'utf8'),{self:{registration:{scope:'https://isolated.invalid/'},addEventListener:(name,fn)=>listeners[name]=fn},caches,Response,URL,crypto:webcrypto,Uint8Array,fetch:async url=>{const a=f.release.assets.find(a=>absolute(a.url)===url);if(options.failed===a.name)throw Error('synthetic network');return new Response(options.mixed===a.name?'HTML_INSTEAD_OF_ASSET':f.contents.get(a.url),{status:options.httpFailure===a.name?404:200});}});
 const event=async name=>{let promise;listeners[name]({waitUntil:p=>promise=p});return promise;};
 const request=async (url,mode='cors')=>{let promise;listeners.fetch({request:{method:'GET',url:absolute(url),mode},respondWith:p=>promise=p});return promise;};
 return {f,maps,deleted,event,request};
}
test('P04: build produces versioned assets, verified HTML and deterministic release',async()=>{const f=await built();for(const a of f.release.assets)assert.equal(sha(f.contents.get(a.url)),a.sha);const html=f.contents.get('./index.html').toString();assert.ok(!html.includes('<script src="storage.js"'));assert.match(html,/<button disabled/);assert.ok(f.release.assets.filter(a=>a.name!=='index.html').every(a=>a.url.includes(a.sha)));});
for(const name of ['storage.js','models.js','calculations.js','app.js'])test('P01/P02/P05: wrong '+name+' blocks startup without touching localStorage',async()=>{const a=await boot({mixed:name});await until(()=>a.nodes.pwaMessage.textContent.includes('保存・削除'));assert.equal(a.ctx.WellBodyRelease.scriptsReady,false);assert.equal(a.executed.length,0);assert.equal(a.writes.length,0);assert.equal(a.buttons[0].disabled,true);assert.equal(a.data.get('wellBodyWeightRecords'),'[{"date":"2020-01-01","weight":80}]');});
test('P09/P10: food failure blocks meals at API, independent weight/plan/custom saves work',async()=>{const a=await boot({failed:'food-master.json'});await until(()=>a.buttons[0].disabled===false&&a.nodes.foodSearchMessage.textContent.includes('停止'));assert.equal(a.ctx.WellBodyRelease.foodReady,false);assert.equal(a.nodes.todayCalories.textContent,'未確認');assert.equal(a.nodes.dashboardKcal.textContent,'未確認');a.run('WellBodyStorage.create().getMeals()');assert.equal(a.run('WellBodyStorage.create().saveMeals([])'),false);assert.equal(a.run('WellBodyStorage.create().clearMeals()'),false);a.nodes.recordDate.value='2020-01-02';a.nodes.recordWeight.value='79';a.run('recordWeight();savePlanAndCalculate()');assert.equal(JSON.parse(a.data.get('wellBodyWeightRecords')).length,2);assert.ok(a.writes.includes('wellBodyPlan'));assert.ok(!a.writes.includes('wellBodyMeals'));a.nodes.customDishName.value='架空料理';for(const id of ['customDishWeight','customDishKcal','customDishProtein','customDishFat','customDishCarbs'])a.nodes[id].value='100';a.run('registerCustomDish()');assert.equal(JSON.parse(a.data.get('wellBodyCustomDishes')).length,1);});
test('P08/P10: verified first boot does not write defaults and permits normal save',async()=>{const a=await boot();await until(()=>a.buttons[0].disabled===false&&a.ctx.WellBodyRelease.foodReady);assert.equal(a.writes.length,0);a.nodes.recordDate.value='2020-01-02';a.nodes.recordWeight.value='79';a.run('recordWeight()');assert.equal(JSON.parse(a.data.get('wellBodyWeightRecords')).length,2);});
for(const options of [{failed:'storage.js'},{mixed:'food-master.json'},{httpFailure:'index.html'},{putFailure:true}])test('P03/P07: failed preparation retains previous and unrelated caches '+JSON.stringify(options),async()=>{const w=await worker(options);await assert.rejects(w.event('install'));assert.deepEqual([...w.maps.keys()].sort(),['other-cache','well-body-app-v4']);assert.equal(w.deleted.length,1);});
test('P04/P05/P07: complete cache serves same release offline, missing assets return 503 not HTML',async()=>{const w=await worker();await w.event('install');await w.event('activate');assert.ok(w.maps.has('other-cache'));assert.ok(w.maps.has('well-body-app-v4'));const r=await w.request('./','navigate');assert.equal(sha(Buffer.from(await r.arrayBuffer())),w.f.release.assets.find(a=>a.name==='index.html').sha);const asset=w.f.release.assets.find(a=>a.name==='storage.js');const r2=await w.request(asset.url);assert.equal(sha(Buffer.from(await r2.arrayBuffer())),asset.sha);const current=w.maps.get('well-body-release-'+w.f.release.id);current.delete(new URL(asset.url,'https://isolated.invalid/').href);await w.event('install');assert.equal((await w.request(asset.url)).status,200);assert.equal((await w.request('./missing.json')).status,503);});
test('P06: worker never forces activation or claims/reloads existing clients',async()=>{const worker=await fs.readFile(path.join(root,'service-worker.js'),'utf8'),boot=await fs.readFile(path.join(root,'pwa-boot.js'),'utf8');assert.doesNotMatch(worker,/skipWaiting\s*\(|clients\.claim\s*\(/);assert.doesNotMatch(boot,/location\.reload\s*\(|postMessage\s*\(/);});
